### ISSUE TITLE
Number multi-valued fields.

### ISSUE THREAD

**Issue by alvar0hurtad0** [factorial-io/entity_scaffolder#13]
## Motivation
In some multi-valued fields is very useful having the count of the element.
## Proposed solution
Add a number on the left of the field like the image:
![Screenshot from 2019-03-22 18-24-54](https://user-images.githubusercontent.com/1130114/54841568-d6f78e00-4ccf-11e9-8885-1f47079bb700.png)

**Comment by d34dman** [comment]
@alvar0hurtad0 thanks for the PR, planning to review over the weekend :) this one is definitely getting in :)

**Comment by alvar0hurtad0** [comment]
@d34dman don't hetisate in asking any modification I'll be able to do.

**Comment by d34dman** [comment]
Thanks for the changes and a nice enhancement :). I am not a fan of working with html concatenation, but that bit can be improved later if possible/needed. And since this is disabled by default, we are not forcing this change in existing projects. Good job!
