### ISSUE TITLE
Add util-and deploy-module to modules_enabled.txt

### ISSUE THREAD

**Issue by stmh** [factorial-io/entity_scaffolder#2]

**Comment by d34dman** [comment]
@stmh  should we replace modules_enabled.txt or append to it?

**Comment by d34dman** [comment]
Right now replacing is easy. Need to introduce support for appending information, if we need that.

**Comment by stmh** [comment]
just add the both module-names as twig variables and let twig render it?

**Comment by d34dman** [comment]
There are few modules that have to be removed from `modules_eabled.txt` to support clean install in local environment. So might as well tackle that in this issue.

**Comment by d34dman** [comment]
This feature has been moved to https://github.com/factorial-io/phabalicious project. So wont fix.
