### ISSUE TITLE
Translation context is not getting exported

### ISSUE THREAD

**Issue by oleg-chemerys** [factorial-io/entity_scaffolder#20]
Recently, when I tried using **drush este** to export strings for translation with context, it was completely ignored (strings were exported, but without any extra context). After digging deeper into the problem I've found we are using modified version of **potx** module, which has an issue with reading new way of arrays declaration (**[]** instead of **array()**). This was already resolved in new version of **potx**, but from what I see - it would be problematic to move to it at the moment. So in this case I would say a good option would be adapting the patch with a fix for newer version of potx to an existing one we use in ES. Link to patch - https://www.drupal.org/files/issues/2598910-20.patch

**Comment by oleg-chemerys** [comment]
Hi @d34dman I've created a pull request https://github.com/factorial-io/entity_scaffolder/pull/21 to fix the issue described above. Could you please check on that?

**Comment by d34dman** [comment]
Thanks for the contribution :) fixed!
